El objetivo es poner el test que esta en jamboard en Julia, para ponerlo despues en `runtests.jl`

1. calcular las matrices
2. obtener el permanetne
3. sumar las tasas

In [2]:
using GroupFunctions

In [3]:
using RandomMatrices

In [4]:
using Immanants

In [5]:
function transformacion(mat)
    n,_ = size(mat)
    for i in 2:n
        mat[i,i-1] = -mat[i,i-1]
    end
    mat
end

transformacion (generic function with 1 method)

## generar matrices unitarias

In [6]:
u1₁ = rand(Haar(2), 2)
u2₁ = rand(Haar(2), 2)
u3₁ = rand(Haar(2), 2)

2×2 Array{Complex{Float64},2}:
  0.384019-0.354167im   0.69438+0.494906im
 -0.692322+0.497781im  0.385484+0.352571im

In [7]:
u1 = zeros(Complex{Float64}, 3,3)
u1[1,1] = 1
u1[2:3,2:3] = u1₁

2×2 Array{Complex{Float64},2}:
 -0.291467-0.363079im  -0.756523-0.459232im
  0.800854+0.376635im  -0.463678-0.0422182im

In [8]:
u2 = zeros(Complex{Float64}, 3,3)
u2[3,3] = 1
u2[1:2,1:2] = u2₁

2×2 Array{Complex{Float64},2}:
 0.298954+0.806458im  0.151223-0.487221im
  0.45432-0.232048im   0.84561+0.157136im

In [9]:
u3 = zeros(Complex{Float64}, 3,3)
u3[1,1] = 1
u3[2:3,2:3] = u3₁

2×2 Array{Complex{Float64},2}:
  0.384019-0.354167im   0.69438+0.494906im
 -0.692322+0.497781im  0.385484+0.352571im

## Idea Original

In [10]:
abs(immanant(Partition([2]), (u1*u2*u3)[[1,2], [1,2]]))^2 + abs(immanant(Partition([2]), (u1*u2*u3)[[1,3], [1,2]]))^2

0.6006119711282845103128322240898439695764585359165798688929672029925109640827868

In [11]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,2], [1,2]]))^2 + abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,3], [1,2]]))^2

0.6006119711282845607327567099474770721948099619879965352465552494827744425820448

In [12]:
abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[1,2], [1,2]]))^2 + abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[1,3], [1,2]]))^2

0.6006119711282845607327567099474770721948099619879965352465552494827744425820448

In [14]:
abs(immanant(Partition([1,1]), transformacion(#=u1*=#(u2*u3)[[1,2], [1,2]])))^2 + abs(immanant(Partition([1,1]), transformacion(#=u1*=#(u2*u3)[[1,3], [1,2]])))^2

0.6006119711282845607327567099474770721948099619879965352465552494827744425820448

In [15]:
p1=abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[1,2], [1,2]]))^2 + abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[1,3], [1,2]]))^2

0.6006119711282845607327567099474770721948099619879965352465552494827744425820448

We have the rate $R(12\to23) + 0.5 R(12\to22) + 0.5 R(12\to33) $

In [18]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.2943082415789709894325778382286824390241249404492827777051618115039513978899166

In [24]:
p2 = abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.2943082415789709993702785435448357963193061869556248469508387261808941837148978

So, we have the possibility of using the previous rate plus this one. The remaining could be added.

We have the rate $R(12\to23) + 0.5 R(12\to22) + 0.5 R(12\to33) + 0.5 R(12\to11)$

In [22]:
abs(immanant(Partition([2]), (u2*u3)[[2,3], [1,2]]))^2+0.5*(abs(immanant(Partition([2]), (u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u2*u3)[[3,3], [1,2]]))^2)

0.3993880288717159065864568713110340977763191882076687912645862775702122748899825

In [25]:
p3 = abs(immanant(Partition([1,1]), transformacion((u2*u3)[[2,3], [1,2]])))^2 +0.5*(abs(immanant(Partition([1,1]), transformacion((u2*u3)[[1,1], [1,2]])))^2 + abs(immanant(Partition([1,1]), transformacion((u2*u3)[[2,2], [1,2]])))^2 + abs(immanant(Partition([1,1]), transformacion((u2*u3)[[3,3], [1,2]])))^2)

0.3993880288717159065864568713110340977763191882076687912645862775702122748899825

Testing that it's a probability distribution

In [28]:
p1 + #= p2 + =# p3

1.000000000000000467319213581258511169971129150195665326511141527052986717472027

## Idea alternativa

In [10]:
p₁₃=[0 0 1; 0 1 0; 1 0 0]
p₁₂=[0 1 0; 1 0 0; 0 0 1]

3×3 Array{Int64,2}:
 0  1  0
 1  0  0
 0  0  1

In [11]:
p₁₃

3×3 Array{Int64,2}:
 0  0  1
 0  1  0
 1  0  0

Primer tasa

In [13]:
abs(immanant(Partition([2]), (u1*u2*u3)[[1,2], [1,2]]))^2 + abs(immanant(Partition([2]), (u1*u2*u3)[[1,3], [1,2]]))^2

0.5219752929756431674632226498201438624534203808036691101743016109823378395962679

In [14]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,2], [1,2]]))^2 + abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,3], [1,2]]))^2

0.5219752929756431049614505751230901173926491902896732320704268836867673270543764

In [117]:
abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[1,2], [1,2]]))^2 + abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[1,3], [1,2]]))^2

0.191090524460995409658891098862741972755531170227512183131582050478413471262043

In [119]:
abs(immanant(Partition([1,1]), transformacion(#=u1*=#(u2*u3)[[1,2], [1,2]])))^2 + abs(immanant(Partition([1,1]), transformacion(#=u1*=#(u2*u3)[[1,3], [1,2]])))^2

0.191090524460995409658891098862741972755531170227512183131582050478413471262043

In [118]:
p1=abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[1,2], [1,2]]))^2 + abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[1,3], [1,2]]))^2

0.191090524460995409658891098862741972755531170227512183131582050478413471262043

Segunda tasa

In [18]:
abs(immanant(Partition([2]), (inv(p₁₃)*u1*u2*u3*p₁₃)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (inv(p₁₃)*u1*u2*u3*p₁₃)[[1,3], [1,2]]))^2

0.1448158515879945739391682670815646453560566450666874105440807733749623018373875

In [19]:
abs(immanant(Partition([2]), (inv(p₁₃)*#=u1*=#u2*u3*p₁₃)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (inv(p₁₃)*#=u1*=#u2*u3*p₁₃)[[1,3], [1,2]]))^2

0.1448158515879945599770580824318991522390740813167413571832251924258920874888368

In [20]:
p2=abs(immanant(Partition([2]), (inv(p₁₃)*#=u1*=#u2*u3*p₁₃)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (inv(p₁₃)*#=u1*=#u2*u3*p₁₃)[[1,3], [1,2]]))^2

0.1448158515879945599770580824318991522390740813167413571832251924258920874888368

Tercer tasa

In [22]:
abs(immanant(Partition([2]), (inv(p₁₂)*u1*u2*u3*p₁₂)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (inv(p₁₂)*u1*u2*u3*p₁₂)[[1,2], [1,2]]))^2

0.5219752929756431674632226498201438624534203808036691101743016109823378395962679

In [23]:
abs(immanant(Partition([2]), (inv(p₁₂)*#=u1*=#u2*u3*p₁₂)[[1,2], [1,2]]))^2+ abs(immanant(Partition([2]), (inv(p₁₂)*#=u1*=#u2*u3*p₁₂)[[2,3], [1,2]]))^2

0.5219752929756431049614505751230901173926491902896732320704268836867673270543764

In [24]:
p3=abs(immanant(Partition([2]), (inv(p₁₂)*#=u1*=#u2*u3*p₁₂)[[1,2], [1,2]]))^2+ abs(immanant(Partition([2]), (inv(p₁₂)*#=u1*=#u2*u3*p₁₂)[[2,3], [1,2]]))^2

0.5219752929756431049614505751230901173926491902896732320704268836867673270543764

In [25]:
lista[1]+lista[2]

LoadError: UndefVarError: lista not defined

In [26]:
p1+p2+p3

1.188766437539280769899959232678079387024372461896087821324078959799426741597589

Tasa fea

In [33]:
kk1 = abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.7411698576893396325429449950275039728244162932216066372239561816555601832245959

In [36]:
#kk1 = abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

In [37]:
kk2 = abs(immanant(Partition([2]), (u1*u2*u3)[[1,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[1,3], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2

0.6294150711553292944725492222837644560051999251454309538111319637930009002896314

In [38]:
lista = [abs(immanant(Partition([2]), (u1*u2*u3)[[1,2], [1,2]]))^2, abs(immanant(Partition([2]), (u1*u2*u3)[[1,3], [1,2]]))^2, abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2]

3-element Array{BigFloat,1}:
 0.4385434943895915941196999795315395767852238928627159144669919191528796630422105
 0.08343179858605157334352267028860428566819648794095319570730969182945817655405632
 0.1074397781796861270093265724636205935517795443417618436368303528106630606933647

In [39]:
kk2 + kk1/2

0.9999999999999991107440217197975164424174080717562342724231100546207809919019294

So, there is a problem. In order to have a sum independent of a $U(2)$ transformation, we require a modification of the network.

# Probando otros cosets

In [44]:
abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2#+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2

0.5055256178544892427419864406813745798527111803202089122783114042046438869892899

In [45]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2#+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2

0.4578414285403887953149201872328260804632193033021456149687480646943982254271077

In [46]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2#+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2

0.0

In [47]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2


0.5652812067200749223242467596964466740149988476439074586055784175050612861204713

In [48]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2

0.4780247070243561424320428603690516962211123865174662329264561203173066134333724

In [49]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ (abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2)/2

0.3363604924498805246667866660800336337833891959928346511212043851578621734069174

In [50]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ (abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2)/2

0.2491039927541617447745827667526386559895027348663934254420820879701075007198185

23 to 22

In [51]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2

0.3430840180145365168102851268097499865234846572431595685824751302615793569286695

In [52]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2

0.4780247070243562470090435662407186958983900201000292432201203223947474441404837

In [53]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ (abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2)/2

0.2252618980971113219098058496366852900376321007924607061096527415361212088110165

In [57]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ (abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2)/2

0.2491039927541617970630831196884721558281415516576749305889141890088279160733742

23 to 33

In [58]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.1551239674937865744363928259121690929412714213598251409463936923209087222555458

In [62]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.02018327848396734711712267313622561575789308321532061795770805562290838800626442

In [60]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ (abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2)/2

0.1312818728367363507228596991878948432465254828507934922916120225657858914744547

In [66]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ (abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2)/2

0.02018327848396734711712267313622561575789308321532061795770805562290838800626442

11 to 22

In [67]:
abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2

0.6934856683752391851158787415789554734349244162035433399143928421453145216624137

In [68]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2

0.9156828570807776952068410803373191606037162401868542402311603314662372815613267

In [69]:
abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.5055256178544892427419864406813745798527111803202089122783114042046438869892899

In [70]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.4578414285403887953149201872328260804632193033021456149687480646943982254271077

In [71]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.2833284291489508372280248077946778923611969899194610222552081169611619577974881

In [72]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.457841428540388899891920893104493080140496936884708625262412266771839056134219

de tres

In [74]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2

0.8009254465549253121252053140425760669867039605453051835512231949559775823557772

In [75]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2

0.9358661355647450423239637534735447763616093234021748581888683870891456695675914

In [76]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2

0.4541826123673057195672659432530983302692417524435335135940267738833203215245704

In [77]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2

0.478024707024356194720543213304885196059751203308747738073288221356027028786928

In [78]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.6129653960341753697513130131449951734044907246619707559151417570153069476826535

In [79]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.4780247070243561424320428603690516962211123865174662329264561203173066134333724

In [80]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.3602025871069307483803197928043078834781351345018662997759860549129850041880085

In [81]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.2491039927541617447745827667526386559895027348663934254420820879701075007198185

 ding ding ding!

In [16]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.5775601923859803886921997547635998430209577926157819870774310328136663195489064

In [17]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.3993880288717158709763022537840850147152908835984339248300719384934462374836528

In [18]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.2943082415789709894325778382286824390241249404492827777051618115039513978899166

In [19]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.2943082415789709993702785435448357963193061869556248469508387261808941837148978

In [116]:
abs(immanant(Partition([1,1]), transformacion(#=u1*=#(u2*u3)[[2,3], [1,2]])))^2+ 0.5*abs(immanant(Partition([1,1]), transformacion(#=u1*=#(u2*u3)[[2,2], [1,2]])))^2+ 0.5*abs(immanant(Partition([1,1]), transformacion(#=u1*=#(u2*u3)[[3,3], [1,2]])))^2

0.7853425223524215589204557964771604516037152860768336999153516768633670930462032

In [104]:
abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[2,3], [1,2]]))^2+ 0.5*abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[2,2], [1,2]]))^2+ 0.5*abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.7617755691658389019330945165647483015413227811756464401802841496236240459438704

In [109]:
0.5*abs(immanant(Partition([1,1]), transformacion(#=u1*=#u2*u3)[[2,2], [1,2]]))^2

0.0

In [110]:
0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2

0.02356695318658265698736127991241215006239250490118725973506752723974304710233301

In [112]:
transformacion(#=u1*=#u2*u3)#[[2,2], [1,2]]

3×3 Array{Complex{Float64},2}:
  0.10388+0.396679im  -0.208188-0.163514im    0.308595-0.816422im
 0.857558+0.310563im  -0.113652+0.0353354im  -0.223453-0.322566im
      0.0+0.0im        0.757878+0.584274im   -0.100171+0.272416im

In [113]:
transformacion(#=u1*=#u2*u3)[[2,2], [1,2]]

2×2 Array{Complex{Float64},2}:
 0.857558+0.310563im  -0.113652+0.0353354im
 0.857558+0.310563im  -0.113652+0.0353354im

In [105]:
u2*u3

3×3 Array{Complex{Float64},2}:
   0.10388+0.396679im  -0.208188-0.163514im    0.308595-0.816422im
 -0.857558-0.310563im  -0.113652+0.0353354im  -0.223453-0.322566im
       0.0+0.0im       -0.757878-0.584274im   -0.100171+0.272416im

In [106]:
transformacion(u2*u3)

3×3 Array{Complex{Float64},2}:
  0.10388+0.396679im  -0.208188-0.163514im    0.308595-0.816422im
 0.857558+0.310563im  -0.113652+0.0353354im  -0.223453-0.322566im
      0.0+0.0im        0.757878+0.584274im   -0.100171+0.272416im

In [86]:
abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.7411698576893396325429449950275039728244162932216066372239561816555601832245959

In [87]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.9156828570807776952068410803373191606037162401868542402311603314662372815613267

In [88]:
abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.5995056431148642139289325911301650266438177982618761260963521231749792043258518

In [89]:
abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[1,1], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[2,2], [1,2]]))^2+ 0.5*abs(immanant(Partition([2]), (#=u1*=#u2*u3)[[3,3], [1,2]]))^2

0.6867621428105832452608806337850726205334677717444999275999541980803177534942172

ding ding ding !

In [101]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2

0.9768147981612917261440217359536196973547826258112352639442470015915845119432387

In [102]:
abs(immanant(Partition([2]), (u1*u2*u3)[[2,3], [1,2]]))^2+0.5*(abs(immanant(Partition([2]), (u1*u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u1*u2*u3)[[3,3], [1,2]]))^2)

0.808909475539004338731244328364662574457967184191639299450770525655320778804524

In [121]:
abs(immanant(Partition([2]), (u2*u3)[[2,3], [1,2]]))^2+0.5*(abs(immanant(Partition([2]), (u2*u3)[[1,1], [1,2]]))^2+ abs(immanant(Partition([2]), (u2*u3)[[2,2], [1,2]]))^2+ abs(immanant(Partition([2]), (u2*u3)[[3,3], [1,2]]))^2)

0.8089094755390042429056491058412941764081000989107817882242048421013116033147228

In [122]:
abs(immanant(Partition([1,1]), transformacion((u2*u3)[[2,3], [1,2]])))^2 +0.5*(abs(immanant(Partition([1,1]), transformacion((u2*u3)[[1,1], [1,2]])))^2 + abs(immanant(Partition([1,1]), transformacion((u2*u3)[[2,2], [1,2]])))^2 + abs(immanant(Partition([1,1]), transformacion((u2*u3)[[3,3], [1,2]])))^2)

0.8089094755390042429056491058412941764081000989107817882242048421013116033147228